---
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*.log
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\w{3} \d{1,2} \d{2}:\d{2}:\d{2}) (?P<host>[^ ]+) (?P<process>[^:]+): (?P<level>[A-Z]+)? ?(?P<message>.*)'
      - labels:
          level:
          process:
          host:
      - timestamp:
          source: timestamp
          format: "Jan 2 15:04:05"

  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*.log
    pipeline_stages:
      - docker: {}
      - labels:
          container_name:
          container_id:
          level:
      - regex:
          expression: '^(?P<timestamp>[^ ]+) (?P<message>.*)'
      - timestamp:
          source: timestamp
          format: RFC3339Nano
