name: CI/CD FullStack App

on:
  push:
    branches:
      - master  # ou main selon ta branche principale

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # requis pour SonarCloud

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        cd backend
        npm install

    - name: Run tests
      run: |
        cd backend
        chmod +x ./node_modules/.bin/jest
        npm test -- --detectOpenHandles
      # continue-on-error: false  # c’est la valeur par défaut donc tu peux l’enlever

    - name: SonarCloud Scan
      uses: SonarSource/sonarqube-scan-action@v5

      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
          args: >
            -Dsonar.projectKey=mousaab02_projetfe
            -Dsonar.organization=mousaab02
            -Dsonar.sources=backend

    - name: Build Docker image
      run: |
        docker build -t moulaa22/projetfe-backend ./backend

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push image to DockerHub
      run: docker push moulaa22/projetfe-backend
    
    - name: Build Frontend Docker image
      run: |
        docker build -t moulaa22/projetfe-frontend ./frontend

    - name: Push Frontend image to DockerHub
      run: docker push moulaa22/projetfe-frontend

    - name: Deploy to Azure VM via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          docker stop projetfe-backend || true
          docker rm projetfe-backend || true
          docker pull moulaa22/projetfe-backend
          docker run -d --name projetfe-backend -p 3000:3000 moulaa22/projetfe-backend
          docker stop projetfe-frontend || true
          docker rm projetfe-frontend || true
          docker pull moulaa22/projetfe-frontend
          docker run -d --name projetfe-frontend -p 80:80 moulaa22/projetfe-frontend

