name: CI/CD Backend Node.js

on:
  push:
    branches:
      - master  # ou main selon ta branche principale

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        cd backend
        npm install

    - name: Run tests
      run: |
        cd backend
        npx test
      continue-on-error: false  #  bloque le pipeline si échec

    - name: Build Docker image
      run: |
        docker build -t moulaa22/projetfe-backend ./backend

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push image to DockerHub
      run: docker push moulaa22/projetfe-backend

    - name: Deploy to Azure VM via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          docker stop projetfe-backend || true
          docker rm projetfe-backend || true
          docker pull moulaa22/projetfe-backend
          docker run -d --name projetfe-backend -p 3000:3000 moulaa22/projetfe-backend
