name: CI/CD Backend Node.js

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Cloner le dépôt
      uses: actions/checkout@v2

    - name: Installer Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Installer les dépendances
      run: npm install
      working-directory: backend

    - name: Tester l'application (optionnel)
      run: npm test || echo "Pas de tests définis"
      working-directory: backend

    - name: Construire l'image Docker
      run: docker build -t moulaa22/projetfe-backend ./backend
    
    - name: Se connecter à Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u moulaa22 --password-stdin
    
    - name: Pousser l'image sur Docker Hub
      run: docker push moulaa22/projetfe-backend    